# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

python:
 # enable access to preinstalled modules (numpy, scipy, matplotlib)
 system_packages: true

# Build documentation in the docs/ directory with Sphinx
sphinx:
 # treat warnings as build errors
 fail_on_warning: true

# Also build downloadable PDF
formats:
 - pdf
 - htmlzip
