[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "PyDiatomic"
dynamic = ["version"]
authors = [{name = "Stephen Gibson", email = "Stephen.Gibson@anu.edu.au"}]
description = "A Python package to solve the time-independent coupled-channel Schr&oumlinger equation using the Johnson renormalized Numerov method"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Developers",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Topic :: Scientific/Engineering :: Physics",
    "Topic :: Scientific/Engineering :: Chemistry",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Programming Language :: Python :: 3.13",
]
requires-python = ">=3.9"
urls = {Homepage = "https://github.com/stggh/PyDiatomic"}
keywords = ["time independent Schrödinger equation", "diatomic", "photodissocation cross section", "wavefunction"]

[project.readme]
file = "README.rst"
content-type = "text/markdown"

[tool.setuptools]
include-package-data = false

[tool.setuptools.packages]
find = {namespaces = false}

[tool.setuptools.dynamic]
version = {attr = "cse.__version__"}
